apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 35
  template:
    metadata:
      labels:
        app: nginx
        version: v2.0
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx
        image: mikiha/nginx:2.0
        resources:
          requests:
            memory: "100M"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /version.html
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 3
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /version.html
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 3
          timeoutSeconds: 3
        ports:
        - containerPort: 80
